"""Include Base models (USR000, USR001)

Revision ID: 04e3dbdf731d
Revises: 04f24c5e075b
Create Date: 2025-11-10 12:48:25.493996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e3dbdf731d'
down_revision = '04f24c5e075b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USR000',
    sa.Column('usr_id', sa.String(length=10), nullable=False, comment='ユーザを一意に表すID'),
    sa.Column('usr_nm', sa.String(length=50), nullable=False, comment='ユーザ氏名'),
    sa.Column('usr_strt_date', sa.Date(), nullable=False, comment='ユーザ利用開始日'),
    sa.Column('usr_end_date', sa.Date(), nullable=True, comment='ユーザ利用終了日'),
    sa.Column('delt_flg', sa.String(length=1), nullable=False, comment='レコード削除フラグ'),
    sa.Column('rec_crtn_prg_id', sa.String(length=50), nullable=True, comment='レコード作成プログラムID'),
    sa.Column('rec_crtn_usr_id', sa.String(length=10), nullable=True, comment='レコード作成ユーザID'),
    sa.Column('rec_crtn_tmstmp', sa.TIMESTAMP(), nullable=True, comment='レコード作成時刻印'),
    sa.Column('rec_upd_prg_id', sa.String(length=50), nullable=True, comment='レコード更新プログラムID'),
    sa.Column('rec_upd_usr_id', sa.String(length=10), nullable=True, comment='レコード更新ユーザID'),
    sa.Column('rec_upd_tmstmp', sa.TIMESTAMP(), nullable=True, comment='レコード更新時刻印'),
    sa.PrimaryKeyConstraint('usr_id')
    )
    op.create_table('USR001',
    sa.Column('usr_id', sa.String(length=10), nullable=False, comment='ユーザID'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='ユーザのログインパスワード（ハッシュ値）'),
    sa.Column('pw_upd_tmstmp', sa.TIMESTAMP(), nullable=True, comment='パスワード更新日時'),
    sa.Column('delt_flg', sa.String(length=1), nullable=False, comment='レコード削除フラグ'),
    sa.Column('rec_crtn_prg_id', sa.String(length=50), nullable=True, comment='レコード作成プログラムID'),
    sa.Column('rec_crtn_usr_id', sa.String(length=10), nullable=True, comment='レコード作成ユーザID'),
    sa.Column('rec_crtn_tmstmp', sa.TIMESTAMP(), nullable=True, comment='レコード作成時刻印'),
    sa.Column('rec_upd_prg_id', sa.String(length=50), nullable=True, comment='レコード更新プログラムID'),
    sa.Column('rec_upd_usr_id', sa.String(length=10), nullable=True, comment='レコード更新ユーザID'),
    sa.Column('rec_upd_tmstmp', sa.TIMESTAMP(), nullable=True, comment='レコード更新時刻印'),
    sa.ForeignKeyConstraint(['usr_id'], ['USR000.usr_id'], ),
    sa.PrimaryKeyConstraint('usr_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USR001')
    op.drop_table('USR000')
    # ### end Alembic commands ###
