"""Recheck all tables

Revision ID: 04f24c5e075b
Revises: 257530767c92
Create Date: 2025-11-10 12:31:37.560145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f24c5e075b'
down_revision = '257530767c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_categories',
    sa.Column('contact_category_id', sa.Integer(), nullable=False),
    sa.Column('contact_category_name', sa.String(length=100), nullable=False),
    sa.Column('deleted_flg', sa.SmallInteger(), nullable=False),
    sa.Column('rec_crtn_prg_id', sa.String(length=50), nullable=False),
    sa.Column('rec_crtn_user_id', sa.String(length=10), nullable=False),
    sa.Column('rec_crtn_tmstmp', sa.DateTime(), nullable=False),
    sa.Column('rec_upd_prg_id', sa.String(length=50), nullable=False),
    sa.Column('rec_upd_user_id', sa.String(length=10), nullable=False),
    sa.Column('rec_upd_tmstmp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('contact_category_id')
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('contact_category_id', sa.Integer(), nullable=True),
    sa.Column('contact_content', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_furigana', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_age', sa.Integer(), nullable=True),
    sa.Column('contact_postal_code', sa.String(length=20), nullable=True),
    sa.Column('contact_prefecture', sa.String(length=50), nullable=True),
    sa.Column('contact_address', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('replied_flg', sa.SmallInteger(), nullable=False),
    sa.Column('deleted_flg', sa.SmallInteger(), nullable=False),
    sa.Column('rec_crtn_prg_id', sa.String(length=50), nullable=False),
    sa.Column('rec_crtn_user_id', sa.String(length=10), nullable=False),
    sa.Column('rec_crtn_tmstmp', sa.DateTime(), nullable=False),
    sa.Column('rec_upd_prg_id', sa.String(length=50), nullable=False),
    sa.Column('rec_upd_user_id', sa.String(length=10), nullable=False),
    sa.Column('rec_upd_tmstmp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_category_id'], ['contact_categories.contact_category_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.drop_table('contact_categories')
    # ### end Alembic commands ###
