"""Create articles table

Revision ID: 3533d653e973
Revises: ec3c9bc7f7c3
Create Date: 2025-11-10 08:40:59.249192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3533d653e973'
down_revision = 'ec3c9bc7f7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('article_image_path', sa.String(length=255), nullable=True),
    sa.Column('article_title', sa.String(length=100), nullable=False),
    sa.Column('article_body', sa.Text(), nullable=False),
    sa.Column('article_category_id', sa.Integer(), nullable=True),
    sa.Column('deleted_flg', sa.SmallInteger(), nullable=False),
    sa.Column('rec_crtn_prg_id', sa.String(length=50), nullable=False),
    sa.Column('rec_crtn_user_id', sa.String(length=10), nullable=False),
    sa.Column('rec_crtn_tmstmp', sa.DateTime(), nullable=False),
    sa.Column('rec_upd_prg_id', sa.String(length=50), nullable=False),
    sa.Column('rec_upd_user_id', sa.String(length=10), nullable=False),
    sa.Column('rec_upd_tmstmp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('article_id')
    )
    #op.drop_table('USR001')
   # op.drop_table('USR000')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USR000',
    sa.Column('usr_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='ユーザを一意に表すID'),
    sa.Column('usr_nm', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='ユーザ氏名'),
    sa.Column('usr_strt_date', sa.DATE(), autoincrement=False, nullable=False, comment='ユーザ利用開始日'),
    sa.Column('usr_end_date', sa.DATE(), autoincrement=False, nullable=True, comment='ユーザ利用終了日'),
    sa.Column('delt_flg', sa.VARCHAR(length=1), autoincrement=False, nullable=False, comment='レコード削除フラグ'),
    sa.Column('rec_crtn_prg_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='レコード作成プログラムID'),
    sa.Column('rec_crtn_usr_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='レコード作成ユーザID'),
    sa.Column('rec_crtn_tmstmp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='レコード作成時刻印'),
    sa.Column('rec_upd_prg_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='レコード更新プログラムID'),
    sa.Column('rec_upd_usr_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='レコード更新ユーザID'),
    sa.Column('rec_upd_tmstmp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='レコード更新時刻印'),
    sa.PrimaryKeyConstraint('usr_id', name='USR000_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('USR001',
    sa.Column('usr_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='ユーザID'),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='ユーザのログインパスワード（ハッシュ値）'),
    sa.Column('pw_upd_tmstmp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='パスワード更新日時'),
    sa.Column('delt_flg', sa.VARCHAR(length=1), autoincrement=False, nullable=False, comment='レコード削除フラグ'),
    sa.Column('rec_crtn_prg_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='レコード作成プログラムID'),
    sa.Column('rec_crtn_usr_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='レコード作成ユーザID'),
    sa.Column('rec_crtn_tmstmp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='レコード作成時刻印'),
    sa.Column('rec_upd_prg_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='レコード更新プログラムID'),
    sa.Column('rec_upd_usr_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='レコード更新ユーザID'),
    sa.Column('rec_upd_tmstmp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='レコード更新時刻印'),
    sa.ForeignKeyConstraint(['usr_id'], ['USR000.usr_id'], name=op.f('USR001_usr_id_fkey')),
    sa.PrimaryKeyConstraint('usr_id', name=op.f('USR001_pkey'))
    )
    op.drop_table('articles')
    # ### end Alembic commands ###
