"""empty message

Revision ID: ea9359977f64
Revises: 04e3dbdf731d
Create Date: 2025-12-01 17:22:56.107767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9359977f64'
down_revision = '04e3dbdf731d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USR000', schema=None) as batch_op:
        batch_op.alter_column('delt_flg',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1),
               existing_comment='レコード削除フラグ',
               existing_nullable=False)

    with op.batch_alter_table('USR001', schema=None) as batch_op:
        batch_op.alter_column('delt_flg',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1),
               existing_comment='レコード削除フラグ',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USR001', schema=None) as batch_op:
        batch_op.alter_column('delt_flg',
               existing_type=sa.String(length=1),
               type_=sa.INTEGER(),
               existing_comment='レコード削除フラグ',
               existing_nullable=False)

    with op.batch_alter_table('USR000', schema=None) as batch_op:
        batch_op.alter_column('delt_flg',
               existing_type=sa.String(length=1),
               type_=sa.INTEGER(),
               existing_comment='レコード削除フラグ',
               existing_nullable=False)

    # ### end Alembic commands ###
